class EffectType():
    MODIFY_ACTION = 3
    MODIFY_ACTOR = 5
    DAMAGE_SHIELD = 7
    REVEAL_ASSET = 8
    INFO = 9
    GRANT_EQ = 10
    GRANT_ADMIN = 11
    REVOKE_ADMIN = 12
    APPLY_DOT = 13
    CURE_DOT = 14
    INSIGHT_PREVENTION = 15
    STEAL_CREDITS = 16
    REVOKE_CREDENTIALS = 17
    REMEDIATE_EXPLOITS = 18